// Code generated by prismic-ts-codegen. DO NOT EDIT.
// To regenerate: npx prismic-ts-codegen

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] } & {};

// --- Settings ---

interface SettingsDocumentDataNavigationItem {
  label: prismic.KeyTextField;
  href: prismic.KeyTextField;
}

interface SettingsDocumentDataSocialLinksItem {
  platform: prismic.SelectField<
    "Facebook" | "X" | "Instagram" | "YouTube"
  >;
  url: prismic.KeyTextField;
}

interface SettingsDocumentData {
  site_title: prismic.KeyTextField;
  site_tagline: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  og_image: prismic.ImageField;
  navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataNavigationItem>
  >;
  address: prismic.KeyTextField;
  phone: prismic.KeyTextField;
  fax: prismic.KeyTextField;
  email: prismic.KeyTextField;
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;
}

export type SettingsDocument = prismic.PrismicDocumentWithoutUID<
  Simplify<SettingsDocumentData>,
  "settings"
>;

// --- Home Page ---

interface HomePageDocumentData {
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>;
}

export type HomePageDocument = prismic.PrismicDocumentWithoutUID<
  Simplify<HomePageDocumentData>,
  "home_page"
>;

// --- Gallery Page ---

interface GalleryPageDocumentData {
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  heading: prismic.KeyTextField;
  subtitle: prismic.KeyTextField;
}

export type GalleryPageDocument = prismic.PrismicDocumentWithoutUID<
  Simplify<GalleryPageDocumentData>,
  "gallery_page"
>;

// --- Plans Page ---

interface PlansPageDocumentData {
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  heading: prismic.KeyTextField;
  subtitle: prismic.KeyTextField;
}

export type PlansPageDocument = prismic.PrismicDocumentWithoutUID<
  Simplify<PlansPageDocumentData>,
  "plans_page"
>;

// --- Service ---

interface ServiceDocumentData {
  title: prismic.KeyTextField;
  description: prismic.KeyTextField;
  image: prismic.ImageField;
  price_label: prismic.KeyTextField;
  duration: prismic.KeyTextField;
  category: prismic.SelectField<"Personal Growth" | "Career Ambitions">;
  sort_order: prismic.NumberField;
}

export type ServiceDocument = prismic.PrismicDocumentWithoutUID<
  Simplify<ServiceDocumentData>,
  "service"
>;

// --- Plan ---

interface PlanDocumentDataFeaturesItem {
  feature_text: prismic.KeyTextField;
}

interface PlanDocumentData {
  name: prismic.KeyTextField;
  description: prismic.KeyTextField;
  price: prismic.NumberField;
  savings: prismic.KeyTextField;
  duration: prismic.KeyTextField;
  featured: prismic.BooleanField;
  features: prismic.GroupField<Simplify<PlanDocumentDataFeaturesItem>>;
  sort_order: prismic.NumberField;
}

export type PlanDocument = prismic.PrismicDocumentWithoutUID<
  Simplify<PlanDocumentData>,
  "plan"
>;

// --- Slices ---

// Hero Slice
export interface HeroSliceDefaultPrimary {
  youtube_video_url: prismic.KeyTextField;
  background_image: prismic.ImageField;
  eyebrow_text: prismic.KeyTextField;
  heading: prismic.KeyTextField;
  subtitle: prismic.KeyTextField;
  cta_text: prismic.KeyTextField;
  cta_link: prismic.KeyTextField;
}

export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceDefault>;

// About Section Slice
export interface AboutSectionSliceDefaultPrimary {
  heading: prismic.KeyTextField;
  body_text: prismic.RichTextField;
  quote_text: prismic.KeyTextField;
  quote_author: prismic.KeyTextField;
  portrait_image: prismic.ImageField;
  cta_text: prismic.KeyTextField;
  cta_link: prismic.KeyTextField;
}

export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceDefault
>;

// Services Preview Slice
export interface ServicesPreviewSliceDefaultPrimary {
  heading: prismic.KeyTextField;
  subtitle: prismic.KeyTextField;
  max_services: prismic.NumberField;
  cta_text: prismic.KeyTextField;
  cta_link: prismic.KeyTextField;
}

export type ServicesPreviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesPreviewSliceDefaultPrimary>,
  never
>;

export type ServicesPreviewSlice = prismic.SharedSlice<
  "services_preview",
  ServicesPreviewSliceDefault
>;

// --- Aggregate Types ---

type HomePageDocumentDataSlicesSlice =
  | HeroSlice
  | AboutSectionSlice
  | ServicesPreviewSlice;

export type AllDocumentTypes =
  | SettingsDocument
  | HomePageDocument
  | GalleryPageDocument
  | PlansPageDocument
  | ServiceDocument
  | PlanDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataSocialLinksItem,
      HomePageDocument,
      HomePageDocumentData,
      GalleryPageDocument,
      GalleryPageDocumentData,
      PlansPageDocument,
      PlansPageDocumentData,
      ServiceDocument,
      ServiceDocumentData,
      PlanDocument,
      PlanDocumentData,
      PlanDocumentDataFeaturesItem,
      HeroSlice,
      HeroSliceDefaultPrimary,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      ServicesPreviewSlice,
      ServicesPreviewSliceDefaultPrimary,
      AllDocumentTypes,
    };
  }
}
